package lab.utils;

public enum StatsGroup {
    SELECTION_NOISE,
    SELECTION_PRESSURE,
    TAKEOVER_TIME,
    SELECTION_INTENSITY,
    GROWTH_RATE,
    REPRODUCTION_RATE,
    LOSS_OF_DIVERSITY,
    SELECTION_DIVERSITY
}
